GET http://localhost:8080/article/


###

POST http://localhost:8080/article/
Content-Type: application/json

{
  "designation": "Snickers",
  "price": 1.99
}

###
POST http://localhost:8080/supplier/
Content-Type: application/json

{
  "name": "Nestle",
  "street": "Rue de la gare",
  "city": "Lausanne",
  "phone": "021 123 45 67",
  "postcode": "1000"
}

###

GET http://localhost:8080/supplier/


###

GET http://localhost:8080/supplier/1
###

PUT http://localhost:8080/supplier/1
Content-Type: application/json

{
  "name": "Nestleeee",
  "street": "Rue de la gare",
  "city": "Lausanneeeee",
  "phone": "021 123 45 67",
  "postcode": "10002"
}

###
DELETE http://localhost:8080/supplier/1

###
POST http://localhost:8080/article/addSupplier
Content-Type: application/json

{
  "supplierId": 1,
  "articleId": 1
}
